name = "customshowers-portal"
compatibility_date = "2024-09-23"

[build]
command = "npm run build"
cwd = "./"

[build.upload]
dir = "dist"
format = "service-worker"

[[routes]]
pattern = "crm.customshowers.uk/*"
zone_name = "customshowers.uk"
